# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache.parallel=true
org.gradle.configureondemand=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1.1
loader_version=0.18.6
loom_version=1.16-SNAPSHOT

# Mod Properties
mod_version=0.0.1
maven_group=io.github.jasminecrash.looksmaxxing

# Dependencies
fabric_api_version=0.145.4+26.1.1

# Mod Metadata
group=io.github.jasminecrash
user=JasmineCrash
slug=looksmaxxing
modId=looksmaxxing
modName=Looksmaxxing
modDescription=Adds the ability to give mobs "The Look", after which they are so enthralled by your charm that they'll follow your commands as if they were units in an RTS game.
authors=JasmineCrash
contributors=JasmineCrash
license=EUPL-1.2
# Branch Metadata
branchName=26.1
compatibleVersions=26.1
compatibleLoaders=fabric

# Enable all Gradle warnings
org.gradle.warning.mode=all